#!/bin/bash

source .env

if [[ $1 == 'pull' ]] || [[ $1 == 'download' ]] || [[ $1 == 'down' ]]; then
    echo pulling
    rclone sync google_drive:passwords.kdbx $(dirname $KDBX_PATH) -P
elif [[ $1 == 'push' ]] || [[ $1 == 'upload' ]] || [[ $1 == 'up' ]]; then
    echo pushing
    echo WARNING: This is a potentially destructive action! [N/y]
    read continue_option

    if [[ ${continue_option,,} == 'y' ]]; then
        echo pushing
        rclone sync -P $KDBX_PATH google_drive:
    else
        echo ABORTED UPLOAD
    fi
else
    echo "Please choose either 'pull' or 'push' option"
fi

